---
title: "BMI and Colorectal Cancer"
subtitle: "BMIN503/EPID600 Final Project"
author: "Antonia Angeli Gazola"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

THIS IS A DRAFT ( 11-05-2024 )

## Overview {#sec-overview}

In my project, I aim to investigate the association between Body Mass Index (BMI) and the age of onset of colorectal cancer. Given the rising incidence of early-onset colorectal cancer and the potential role of lifestyle factors like diet and obesity, I plan to explore my hypothesis that higher BMI may be linked to an earlier onset of colorectal cancer in patients. To address this, I will analyze data from the Colorectal Cancer (MSK, JNCI 2021) dataset, available on cBioPortal, which includes detailed patient information.

To strengthen my approach, I consulted Dr. Gary Weissman, an Assistant Professor in Pulmonary and Critical Care Medicine and Informatics, who provided guidance on refining research questions, dataset selection, and data analysis methods from a clinical perspective. Nicholas Bishop, a Clinical Research Coordinator, offered valuable advice on methodological approaches to working with the dataset and data visualization techniques. Both were instrumental in shaping the project’s direction and execution.

## Introduction {#sec-introduction}

Globally, the incidence of colorectal cancer (CRC) is shifting. In high-income countries, rates of CRC in individuals over 50 have stabilized or declined, while rates among those under 50 are increasing for reasons not yet fully understood. This trend highlights the importance of researching the specific risk factors in younger CRC patients, as identifying modifiable factors such as obesity could be key to developing prevention strategies tailored to younger adults. While obesity is a known risk factor for CRC, most research has focused on older populations, leaving gaps in our understanding of BMI’s role in CRC among younger individuals. Recent research has found a link between higher body mass index (BMI) and earlier onset of CRC, suggesting that being overweight or obese may play a key role in CRC development in young adults. However, it remains uncertain whether these associations differ by sex or other demographic factors, which could be crucial for creating personalized prevention strategies. This study uses data from 1,516 CRC cases, including a range of ages, from the MSK Colorectal Cancer dataset to explore the relationship between BMI and age of CRC diagnosis.

This research is interdisciplinary, integrating epidemiology, data science, biostatistics, medicine, oncology, and public health. Insights from Dr. Weissman’s clinical and biostatistical expertise, along with Nicholas Bishop’s methodological guidance, enrich this study, aiming to enhance our understanding of CRC in younger patients and contribute to advancements in oncology prevention strategies.

## Methods {#sec-methods}

Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked here.
